services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: eduki
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - app_storage:/var/www/html/storage
        ports:
            - "8000:9000"
            - "9003:9003"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: eduki
            DB_USERNAME: eduki
            DB_PASSWORD: Qwerty_123
            XDEBUG_MODE: develop,debug
        depends_on:
            - mysql

    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "81:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: eduki
            MYSQL_ROOT_PASSWORD: Qwerty_123
            MYSQL_USER: eduki
            MYSQL_PASSWORD: Qwerty_123
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3307:3306"

    composer:
        image: composer:latest
        volumes:
            - .:/app
        command: ["tail", "-f", "/dev/null"]

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]
        depends_on:
            - mysql

#    behat:
#        image: behat/test-suite-image:latest
#        depends_on:
#            - nginx
#        command: [ "tail", "-f", "/dev/null" ]

volumes:
    dbdata:
    app_storage:
